/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class audiorecord_messcat_com_mediorecorddemo_ffmpeg_FFmpegRun_FFmpegRunListener */

#ifndef _Included_audiorecord_messcat_com_mediorecorddemo_ffmpeg_FFmpegRun_FFmpegRunListener
#define _Included_audiorecord_messcat_com_mediorecorddemo_ffmpeg_FFmpegRun_FFmpegRunListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
