/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class audiorecord_messcat_com_mediorecorddemo_ffmpeg_FFmpegRun */

#ifndef _Included_audiorecord_messcat_com_mediorecorddemo_ffmpeg_FFmpegRun
#define _Included_audiorecord_messcat_com_mediorecorddemo_ffmpeg_FFmpegRun
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     audiorecord_messcat_com_mediorecorddemo_ffmpeg_FFmpegRun
 * Method:    run
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_audiorecord_messcat_com_mediorecorddemo_ffmpeg_FFmpegRun_run
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
